const express = require('express')
const router = express.Router()
const controller = require('../../controllers/view/views')
const middleware = require('../../middleware/authentication')

router.get('/viewUnggahProposal', controller.unggahProposal)
router.get('/unggahBalasanView', controller.unggahBalasan)
router.get('/updateProposalView', controller.updateProposal)
router.get('/updateBalasanView', controller.updateBalasan)
router.get('/fileView', controller.displayFiles)
router.get('/suratBalasanView', controller.suratBalasan)
router.get('/login', controller.login)
router.get('/login/sekjur', controller.loginSekjur)
router.get('/suratTugas', controller.suratTugas)
router.get('/suratTugas/view/:id', controller.suratTugasView)
router.get('/suratPengantar', controller.suratPengantar)
router.get('/suratPengantar/view/:id', controller.suratPengantarView)
router.get('/dataMahasiswa', controller.dataMahasiswa)
router.get('/tambahDosen/:id', controller.tambahDosen)
router.get('/pengajuanSuratTugas', controller.pengajuanSuratTugas)
router.get('/pengajuanSuratPengantar', controller.pengajuanSuratPengantar)

module.exports = router